---
title: "Comparison Plot Reports"
author: "Peter von Rohr"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comparison Plot Reports}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Comparison plot reports are pdf-documents that summarize a comparison between a series of plots that are drawn for two different routine genetic evaluation (GE) runs. The corresponding plots from the two GE-runs are drawn side-by-side allowing for a seamless comparison of the results from the two different GE runs. 


## Genetic Evaluation (GE)
GE analysis uses linear mixed effect models which are mostly animal models with a few exceptions where also sire models are used. In animal models, the breeding value of an animal is included into the model as random effect. Sire models contain random sire effects. Breeding values are realised solutions of the random effects. Between two successive GE-runs the solutions for most animals included in the analysis are supposed to stay constant. As a consequence of that plots of breeding values from two different GE-runs would result mostly in points that are aligned along the 45-degree line. 

The second quality measure besides the scatter plots is the correlation between the results of two subsequent evaluations. The correlation coefficient of the results of two subsequent GE-runs must be above .99. Having the scatterplots and the correlation coefficients of two GE-runs side-by-side next to each other 


## Quality Measure
One of the quality measure that is used are the plots of the predicted breeding values from two different runs. 
