---
title: "zwsroutinetools"
author: "Peter von Rohr"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{zwsroutinetools}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


The package `zwsroutinetools` is an experimental package and a sandbox for a package called `geRt` which is released later and includes the production version of all the tools. In this package, we start experiments of new things and want to test different ideas. Both packages `zwsroutinetools` and `geRt` both contain utility functions and tools that are useful for working with data and outputs of a routine genetic evaluation (GE) analysis run. It has to be noted that the tools are explicitly tailored according to the needs in the context of Qualitas AG. The aspect of providing generic general purpose tools is not of primary focus here. 


## Useful Tools
Tools that are considered to be useful are grouped into different categories. So far, the following categories where tools are to be developed, were identified

1. quality assurance
2. result collection and gathering


## Quality Assurance
Quality assurance has become a very important aspect in every data analysis and in data science in general. Although questions like when is a data analysis a good data analysis are still a matter of debate and are far from being definitively answered, we can come up with a few criteria that help us to identify potential quality problems in the analyses performed during a GE-routine run.

The GE-routine runs are done regularly in a sequence. From one analysis to the next, only a small protion of the input data changes. As a consequence of that the results are expected to stay more or less constant. Hence the correlation between the predicted breeding values for all animals with prediction results in two subsequence GE-runs should be between $0.99$ and $1$.  




